version: "3.1"

services:
  ui:
    build:
      context: ./ui
      dockerfile: ./ui/Dockerfile
    restart: always
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    restart: always
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}
      APP_URL: ${APP_URL}

  reverse-proxy:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ui
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
