name: Docker Build
description: Builds a Docker image using a private SSH key to access private repositories

inputs:
  image:
    description: Image identifier
    required: false

runs:
  using: composite
  steps:
    - uses: ./.github/actions/docker-login
    - uses: ./.github/actions/load-vault-secrets
      id: vault
      with:
        secrets: |
          kv/data/github-ci NPMRC
    - uses: ./.github/actions/create-npmrc
      with:
        npmrc: ${{ fromJson(steps.vault.outputs.secrets).NPMRC }}
    - name: Build
      shell: bash
      run: |
        if [ -z "${{ inputs.image }}" ]; then
          image=""
        else
          image="-${{ inputs.image }}"
        fi
        make "build$image"
